"""refactor to game-player model

Revision ID: 0490a4803d3a
Revises: 6dce6dca0335
Create Date: 2026-06-27 15:14:16.117996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0490a4803d3a'
down_revision = '6dce6dca0335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('playerid', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('ones', sa.Integer(), nullable=True),
    sa.Column('twos', sa.Integer(), nullable=True),
    sa.Column('threes', sa.Integer(), nullable=True),
    sa.Column('fours', sa.Integer(), nullable=True),
    sa.Column('fives', sa.Integer(), nullable=True),
    sa.Column('sixes', sa.Integer(), nullable=True),
    sa.Column('threex', sa.Integer(), nullable=True),
    sa.Column('fourx', sa.Integer(), nullable=True),
    sa.Column('fullhouse', sa.Integer(), nullable=True),
    sa.Column('small', sa.Integer(), nullable=True),
    sa.Column('large', sa.Integer(), nullable=True),
    sa.Column('yahtzee', sa.Integer(), nullable=True),
    sa.Column('chance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_playerid'), ['playerid'], unique=False)

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_bonus'))
        batch_op.drop_index(batch_op.f('ix_score_chance'))
        batch_op.drop_index(batch_op.f('ix_score_fives'))
        batch_op.drop_index(batch_op.f('ix_score_fours'))
        batch_op.drop_index(batch_op.f('ix_score_fourx'))
        batch_op.drop_index(batch_op.f('ix_score_full'))
        batch_op.drop_index(batch_op.f('ix_score_fullhouse'))
        batch_op.drop_index(batch_op.f('ix_score_large'))
        batch_op.drop_index(batch_op.f('ix_score_name'))
        batch_op.drop_index(batch_op.f('ix_score_ones'))
        batch_op.drop_index(batch_op.f('ix_score_playerid'))
        batch_op.drop_index(batch_op.f('ix_score_sixes'))
        batch_op.drop_index(batch_op.f('ix_score_small'))
        batch_op.drop_index(batch_op.f('ix_score_subtotalupper'))
        batch_op.drop_index(batch_op.f('ix_score_threes'))
        batch_op.drop_index(batch_op.f('ix_score_threex'))
        batch_op.drop_index(batch_op.f('ix_score_total'))
        batch_op.drop_index(batch_op.f('ix_score_totallower'))
        batch_op.drop_index(batch_op.f('ix_score_totaluppersection'))
        batch_op.drop_index(batch_op.f('ix_score_twos'))
        batch_op.drop_index(batch_op.f('ix_score_yahtzee'))

    op.drop_table('score')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_nextplayer'))
        batch_op.drop_index(batch_op.f('ix_game_numberofplayers'))
        batch_op.drop_index(batch_op.f('ix_game_playerfive'))
        batch_op.drop_index(batch_op.f('ix_game_playerfour'))
        batch_op.drop_index(batch_op.f('ix_game_playerone'))
        batch_op.drop_index(batch_op.f('ix_game_playerthree'))
        batch_op.drop_index(batch_op.f('ix_game_playertwo'))
        batch_op.drop_column('playerfive')
        batch_op.drop_column('playerone')
        batch_op.drop_column('playerfour')
        batch_op.drop_column('playertwo')
        batch_op.drop_column('playerthree')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playerthree', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('playertwo', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('playerfour', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('playerone', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('playerfive', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_playertwo'), ['playertwo'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_playerthree'), ['playerthree'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_playerone'), ['playerone'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_playerfour'), ['playerfour'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_playerfive'), ['playerfive'], unique=1)
        batch_op.create_index(batch_op.f('ix_game_numberofplayers'), ['numberofplayers'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_nextplayer'), ['nextplayer'], unique=False)

    op.create_table('score',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('ones', sa.VARCHAR(length=64), nullable=True),
    sa.Column('twos', sa.VARCHAR(length=64), nullable=True),
    sa.Column('threes', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fours', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fives', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subtotalupper', sa.INTEGER(), nullable=True),
    sa.Column('bonus', sa.INTEGER(), nullable=True),
    sa.Column('totaluppersection', sa.INTEGER(), nullable=True),
    sa.Column('threex', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fourx', sa.VARCHAR(length=64), nullable=True),
    sa.Column('fullhouse', sa.VARCHAR(length=64), nullable=True),
    sa.Column('small', sa.VARCHAR(length=64), nullable=True),
    sa.Column('large', sa.VARCHAR(length=64), nullable=True),
    sa.Column('yahtzee', sa.VARCHAR(length=64), nullable=True),
    sa.Column('chance', sa.VARCHAR(length=64), nullable=True),
    sa.Column('totallower', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('playerid', sa.INTEGER(), nullable=True),
    sa.Column('sixes', sa.VARCHAR(length=64), nullable=True),
    sa.Column('full', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_yahtzee'), ['yahtzee'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_twos'), ['twos'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_totaluppersection'), ['totaluppersection'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_totallower'), ['totallower'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_total'), ['total'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_threex'), ['threex'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_threes'), ['threes'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_subtotalupper'), ['subtotalupper'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_small'), ['small'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_sixes'), ['sixes'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_playerid'), ['playerid'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_ones'), ['ones'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_large'), ['large'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fullhouse'), ['fullhouse'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_full'), ['full'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fourx'), ['fourx'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fours'), ['fours'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fives'), ['fives'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_chance'), ['chance'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_bonus'), ['bonus'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_playerid'))

    op.drop_table('player')
    # ### end Alembic commands ###
