"""score table

Revision ID: 3c9fcfbd6173
Revises: 39b32c306652
Create Date: 2023-05-17 15:26:37.086319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9fcfbd6173'
down_revision = '39b32c306652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ones', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('twos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('threes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fives', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sixed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('subtotalupper', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totaluppersection', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('threex', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fourx', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fullhouse', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('large', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('yahtzee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('chance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('totallower', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_score_name')
        batch_op.create_index(batch_op.f('ix_score_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_bonus'), ['bonus'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_chance'), ['chance'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fives'), ['fives'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fours'), ['fours'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fourx'), ['fourx'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_fullhouse'), ['fullhouse'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_large'), ['large'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_ones'), ['ones'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_sixed'), ['sixed'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_small'), ['small'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_subtotalupper'), ['subtotalupper'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_threes'), ['threes'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_threex'), ['threex'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_total'), ['total'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_totallower'), ['totallower'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_totaluppersection'), ['totaluppersection'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_twos'), ['twos'], unique=False)
        batch_op.create_index(batch_op.f('ix_score_yahtzee'), ['yahtzee'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_yahtzee'))
        batch_op.drop_index(batch_op.f('ix_score_twos'))
        batch_op.drop_index(batch_op.f('ix_score_totaluppersection'))
        batch_op.drop_index(batch_op.f('ix_score_totallower'))
        batch_op.drop_index(batch_op.f('ix_score_total'))
        batch_op.drop_index(batch_op.f('ix_score_threex'))
        batch_op.drop_index(batch_op.f('ix_score_threes'))
        batch_op.drop_index(batch_op.f('ix_score_subtotalupper'))
        batch_op.drop_index(batch_op.f('ix_score_small'))
        batch_op.drop_index(batch_op.f('ix_score_sixed'))
        batch_op.drop_index(batch_op.f('ix_score_ones'))
        batch_op.drop_index(batch_op.f('ix_score_large'))
        batch_op.drop_index(batch_op.f('ix_score_fullhouse'))
        batch_op.drop_index(batch_op.f('ix_score_fourx'))
        batch_op.drop_index(batch_op.f('ix_score_fours'))
        batch_op.drop_index(batch_op.f('ix_score_fives'))
        batch_op.drop_index(batch_op.f('ix_score_chance'))
        batch_op.drop_index(batch_op.f('ix_score_bonus'))
        batch_op.drop_index(batch_op.f('ix_score_name'))
        batch_op.create_index('ix_score_name', ['name'], unique=False)
        batch_op.drop_column('total')
        batch_op.drop_column('totallower')
        batch_op.drop_column('chance')
        batch_op.drop_column('yahtzee')
        batch_op.drop_column('large')
        batch_op.drop_column('small')
        batch_op.drop_column('fullhouse')
        batch_op.drop_column('fourx')
        batch_op.drop_column('threex')
        batch_op.drop_column('totaluppersection')
        batch_op.drop_column('bonus')
        batch_op.drop_column('subtotalupper')
        batch_op.drop_column('sixed')
        batch_op.drop_column('fives')
        batch_op.drop_column('fours')
        batch_op.drop_column('threes')
        batch_op.drop_column('twos')
        batch_op.drop_column('ones')

    # ### end Alembic commands ###
