"""score table

Revision ID: 6ae730252af7
Revises: abb7b44c4d5a
Create Date: 2023-05-17 19:03:27.942462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae730252af7'
down_revision = 'abb7b44c4d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sixes', sa.String(length=64), nullable=True))
        batch_op.alter_column('ones',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('twos',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('threes',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('fours',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('fives',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('threex',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('fourx',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('fullhouse',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('small',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('large',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('yahtzee',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('chance',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.drop_index('ix_score_sixed')
        batch_op.create_index(batch_op.f('ix_score_sixes'), ['sixes'], unique=False)
        batch_op.drop_column('sixed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sixed', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_score_sixes'))
        batch_op.create_index('ix_score_sixed', ['sixed'], unique=False)
        batch_op.alter_column('chance',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('yahtzee',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('large',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('small',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fullhouse',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fourx',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('threex',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fives',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('fours',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('threes',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('twos',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('ones',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('sixes')

    # ### end Alembic commands ###
