"""full score card 

Revision ID: 6dce6dca0335
Revises: 6ae730252af7
Create Date: 2023-05-17 22:42:18.780257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dce6dca0335'
down_revision = '6ae730252af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_score_full'), ['full'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_full'))
        batch_op.drop_column('full')

    # ### end Alembic commands ###
