"""score table

Revision ID: abb7b44c4d5a
Revises: 3c9fcfbd6173
Create Date: 2023-05-17 15:44:37.671453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb7b44c4d5a'
down_revision = '3c9fcfbd6173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playerid', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_score_playerid'), ['playerid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_playerid'))
        batch_op.drop_column('playerid')

    # ### end Alembic commands ###
