"""add shareable game code

Revision ID: cf40ee04265c
Revises: 0490a4803d3a
Create Date: 2026-06-27 16:01:04.220508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf40ee04265c'
down_revision = '0490a4803d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=8), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_code'), ['code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_code'))
        batch_op.drop_column('code')

    # ### end Alembic commands ###
